name: 改善提案
description: 既存機能の改善や、より良い方法を提案します
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        この機能要望は、@Tsubu-Server/Owner チームに通知されます。
        ---
  - type: input
    id: bug-summary
    attributes:
      label: 修正点の概要
      description: どのような点を修正する必要がありますか？
      placeholder: 検索機能のパフォーマンス向上
    validations:
      required: true
  - type: textarea
    id: current-situation
    attributes:
      label: 現状と問題点
      description: 現在の状況と、なぜ改善が必要だと考えるのかを説明してください。
      placeholder: 現在の検索は大規模なデータセットで非常に遅く、ユーザーエクスペリエンスを損ねている。
    validations:
      required: true
  - type: textarea
    id: benefits
    attributes:
      label: 期待される効果
      description: この改善によってどのような利益が得られると期待しますか？
      placeholder: 速度が50%向上し、ユーザーの離脱率が減少する。
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: その他の情報 (任意)
      description: 参考になる情報、スクリーンショット、図などがあれば添付してください。
